### ISSUE TITLE
Unable to edit pull request and push events programatically 

### ISSUE THREAD

**Issue by JananiJM** [moveworkforward/bitbucket-webhooks-plugin#115]
i am trying to set / unset checkboxes under push and pull request events in webhooks configuration page using rest api . 

this url doesnt work for setting events -  http://{host}/rest/webhook/1.0/projects/{projectkey}/repos/{repo}/configurations.

Suggest me a solution for this please. 
thanks in advance

**Comment by JananiJM** [comment]
@Eernie ...is there a solution similar to https://github.com/Eernie/bitbucket-webhooks-plugin/issues/29

**Comment by eoc-ross** [comment]
Solved with #130
