### ISSUE TITLE
API verbs are incorrect

### ISSUE THREAD

**Issue by esmaras** [moveworkforward/bitbucket-webhooks-plugin#125]
I noticed that the api verbs are incorrect when I was coding up a simple script to create and update webhooks in this plugin. To create a webhook a "PUT" is required by this API and to update a webhook a "POST" is required. This led to a lot of confusion as I was getting errors when I tried to follow the standard API verb convention to create a new webhook using an HTTP POST.

Here is the documentation I found from Jenkins on using the API:
https://support.cloudbees.com/hc/en-us/articles/115000083932?input_string=multibranch+pipelines+set+post+webhooks+in+bitbucket

Here is a general chart of REST API verbs and their uses:
https://www.restapitutorial.com/lessons/httpmethods.html

Also, it would be helpful if there was additional documentation on using the API somewhere official (maybe in the README here at the very least), rather than through Jenkins.

**Comment by casz** [comment]
Your welcome to submit a PR

**Comment by esmaras** [comment]
@casz ok I will :)

**Comment by casz** [comment]
Just consider it requires to be backwards compatible 😅😇

**Comment by dminca** [comment]
The issue is valid. I also tried to **UPDATE** a POST Webhook with **PUT** and I was getting **405** response all the time.

But after I tried via **POST** it went through 😉 

Here's a sample Golang request:

```go
# webhooks looks like this
[{151 Jenkins https://example.com/bitbucket-scmsource-hook/notify   true}]
```

```go
type POSTWebhook []struct {
	ID                 int    `json:"id,omitempty"`
	Title              string `json:"title"`
	URL                string `json:"url"`
	CommittersToIgnore string `json:"committersToIgnore"`
	BranchesToIgnore   string `json:"branchesToIgnore"`
	Enabled            bool   `json:"enabled"`
}

var hook = POSTWebhook{
		{
			ID: 0,
			Title:              "testFromGolang2",
			URL:                "",
			CommittersToIgnore: "",
			BranchesToIgnore:   "",
			Enabled:            false,
		},
	}
	log.Printf("%v", hook)
	data, err := json.Marshal(hook[0])
	if err != nil {
		panic(err)
	}

	log.Printf("%v", string(data))
	req, err := http.NewRequest(http.MethodPost, APIURL + "/rest/webhook/1.0/projects/" + PROJECT_ID + "/repos/my-repo/configurations/" + strconv.Itoa(webhooks[0][1].ID), bytes.NewBuffer(data))
	if err != nil {
		panic(err)
	}

	// set the request header Content-Type for json
	req.Header.Set("Content-Type", "application/json")
	req.SetBasicAuth("user", "password")
	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	log.Printf("%v", resp.StatusCode)
```

**Comment by leonkyr** [comment]
We will plan the API docs AND a new API version.
