### ISSUE TITLE
No hooks of this type have been installed

### ISSUE THREAD

**Issue by antonin07130** [moveworkforward/bitbucket-webhooks-plugin#134]
After installing this plugin to bitbucket server from docker image atlassian/bitbucket-server:5.10.0, in the Hooks configuration of project, "No hooks of this type have been installed".

Thus i cannot use the plugin.

**Comment by casz** [comment]
if your using 5.10.0 you can use the native webhook suppport?

**Comment by leonkyr** [comment]
There is no much info provided to address this issue @antonin07130 (if possible please provide more)
